### PR TITLE
added handwashing raw data

### PR DESCRIPTION
**Pull request by nahid18**
Added two raw (.csv) dataset for handwashing from DataCamp into the data-raw folder.
R Analysis and other files will be added later today.
Please accept the pull request.

### CODE REVIEW

**Comment by s-andrews** [comment]
Do you have a URL for the original source of these files please.  Also if there's a pointer to a licence under which they are available that would be super helpful.

**Comment by nahid18** [comment]
Where should I add the data source link and license? In this comment section?

**Comment by s-andrews** [comment]
In the first instance yes, just here will be OK.  Eventually there is a table which records the origins of all of the datasets so we'll add that information to it.

**Comment by nahid18** [comment]
Ok thanks. I will take a few minutes and add the data source link and license in here.

**Comment by nahid18** [comment]
The dataset is from here:
https://www.kaggle.com/arijit75/survey-data

License is unknown. Should I be concerned about that?

**Comment by nahid18** [comment]
I have contacted datacamp.com about the license. I will update here once I get a reply from them.

**Comment by s-andrews** [comment]
Thanks we just need to be a little careful that we don't distribute content which is claimed by another group.  If this is data taken from an original publication then we can always go back to the original source.

**Comment by nahid18** [comment]
Got it. Kindly wait till I hear about the license from them.

**Comment by StevenWingett** [comment]
Ok.  I will wait for this confirmation until I merge the branch.

Thanks very much!

**Comment by nahid18** [comment]
Hi, I have just got a reply from the person who provided the dataset. 
From his words, the dataset is under public domain and scrapped from Wikipedia, and cannot be copyrighted.
Here's his reply: [https://twitter.com/rabaath/status/1308496328872222720](https://twitter.com/rabaath/status/1308496328872222720)
For context, Mr Rasmus Bååth used this dataset as a guided project in datacamp.com

Here's few more links that can be helpful:

1. [https://en.wikipedia.org/wiki/Ignaz_Semmelweis](https://en.wikipedia.org/wiki/Ignaz_Semmelweis)
2. [https://en.wikipedia.org/wiki/Historical_mortality_rates_of_puerperal_fever](https://en.wikipedia.org/wiki/Historical_mortality_rates_of_puerperal_fever)

So I think, the dataset is copyright free and can be redistributed as a nice little life science training dataset for analysis.

**Comment by nahid18** [comment]
I have also received a reply from the DataCamp support, and they said the dataset usage is allowable as long as we are "referencing DataCamp as the source".
Source: [datacamp.com](https://datacamp.com)
I think, adding a reference won't hurt and it will be a good little dataset.

**Comment by s-andrews** [comment]
Excellent - thanks for providing that clarification.

**Pull request closed without merging**
